import enum


class PeggleNightsAPGoals(enum.Enum):
    SHADOW_PEGS_FINAL_LEVEL = 0
    SHADOW_PEG_HUNT = 1


class PeggleNightsAPItems(enum.Enum):
    SHADOW_PEG = "Shadow Peg"
    BRITTLE_PEG = "Brittle Peg"
    CHIPPED_PEG = "Chipped Peg"
    DENTED_PEG = "Dented Peg"
    HOLLOW_PEG = "Hollow Peg"
    PROGRESSIVE_FEVER_METER = "Progressive Fever Meter Threshold"
    PROGRESSIVE_STARTING_BALL_INCREASE = "Progressive Starting Ball Increase"
    RUSTY_PEG = "Rusty Peg"
    CHARACTER_UNLOCK_BJORN = "Master Unlock: Bjorn"
    CHARACTER_UNLOCK_JIMMY_LIGHTNING = "Master Unlock: Jimmy Lightning"
    CHARACTER_UNLOCK_KAT_TUT = "Master Unlock: Kat Tut"
    CHARACTER_UNLOCK_SPLORK = "Master Unlock: Splork"
    CHARACTER_UNLOCK_CLAUDE = "Master Unlock: Claude"
    CHARACTER_UNLOCK_RENFIELD = "Master Unlock: Renfield"
    CHARACTER_UNLOCK_TULA = "Master Unlock: Tula"
    CHARACTER_UNLOCK_WARREN = "Master Unlock: Warren"
    CHARACTER_UNLOCK_LORD_CINDERBOTTOM = "Master Unlock: Lord Cinderbottom"
    CHARACTER_UNLOCK_MASTER_HU = "Master Unlock: Master Hu"
    CHARACTER_UNLOCK_MARINA = "Master Unlock: Marina"


class PeggleNightsAPMasterSelectionModes(enum.Enum):
    SINGLE_MASTER = 0
    MULTIPLE_MASTERS = 1


class PeggleNightsAPRequirementModes(enum.Enum):
    SAME_FOR_ALL_LEVELS = 0
    RANDOM_PER_LEVEL = 1


class PeggleNightsAPTags(enum.Enum):
    ANTITOXIC_ITEM = "2-3 Antitoxic Item"
    ANTITOXIC_LOCATION = "2-3 Antitoxic Location"
    ARRIVANCE_ITEM = "5-2 Arrivance Item"
    ARRIVANCE_LOCATION = "5-2 Arrivance Location"
    AU_REVOIR_ITEM = "6-5 Au Revoir Item"
    AU_REVOIR_LOCATION = "6-5 Au Revoir Location"
    BEATS_DRIVING_ITEM = "9-2 Beats Driving Item"
    BEATS_DRIVING_LOCATION = "9-2 Beats Driving Location"
    BJORN_IDENTITY_ITEM = "1-5 Bjorn Identity Item"
    BJORN_IDENTITY_LOCATION = "1-5 Bjorn Identity Location"
    BLOOMIN_ITEM = "14-2 Bloomin' Item"
    BLOOMIN_LOCATION = "14-2 Bloomin' Location"
    BLUE_SLOUGH_ITEM = "13-5 Blue Slough Item"
    BLUE_SLOUGH_LOCATION = "13-5 Blue Slough Location"
    BOWL_OF_DROME_ITEM = "5-1 Bowl Of Drome Item"
    BOWL_OF_DROME_LOCATION = "5-1 Bowl Of Drome Location"
    BREAKTHROUGH_ITEM = "2-4 Breakthrough Item"
    BREAKTHROUGH_LOCATION = "2-4 Breakthrough Location"
    BRRRZAP_ITEM = "2-2 Brrrzap! Item"
    BRRRZAP_LOCATION = "2-2 Brrrzap! Location"
    CALL_FOR_HELP_ITEM = "1-2 Call For Help Item"
    CALL_FOR_HELP_LOCATION = "1-2 Call For Help Location"
    CHARACTER_UNLOCK_ITEM = "Character Unlock Item"
    CRIMEWAVE_ITEM = "1-1 Crimewave Item"
    CRIMEWAVE_LOCATION = "1-1 Crimewave Location"
    DEATH_DEFYING_ITEM = "4-5 Death Defying Item"
    DEATH_DEFYING_LOCATION = "4-5 Death Defying Location"
    DIPLOMA_SEE_ITEM = "11-5 Diploma, See? Item"
    DIPLOMA_SEE_LOCATION = "11-5 Diploma, See? Location"
    EIFFEL_POWER_ITEM = "6-3 Eiffel Power Item"
    EIFFEL_POWER_LOCATION = "6-3 Eiffel Power Location"
    EXPERIMENT_X_ITEM = "2-1 Experiment X Item"
    EXPERIMENT_X_LOCATION = "2-1 Experiment X Location"
    EXPLODIOUS_ITEM = "5-4 Explodious Item"
    EXPLODIOUS_LOCATION = "5-4 Explodious Location"
    FEEL_THE_NOIZE_ITEM = "10-5 Feel The Noize Item"
    FEEL_THE_NOIZE_LOCATION = "10-5 Feel The Noize Location"
    FEVER_METER_LOCATION = "Fever Meter Location"
    FILLER_ITEM = "Filler Item"
    FIRE_EATER_ITEM = "8-4 Fire Eater Item"
    FIRE_EATER_LOCATION = "8-4 Fire Eater Location"
    FLUFFY_SUNNIES_ITEM = "14-5 Fluffy Sunnies Item"
    FLUFFY_SUNNIES_LOCATION = "14-5 Fluffy Sunnies Location"
    FOUNDING_FATHERS_ITEM = "7-1 Founding Fathers Item"
    FOUNDING_FATHERS_LOCATION = "7-1 Founding Fathers Location"
    FULL_CLEAR_LOCATION = "Full Clear Location"
    GOAL_ITEM = "Goal Item"
    GREAT_BALL_OF_IRE_ITEM = "9-5 Great Ball of Ire Item"
    GREAT_BALL_OF_IRE_LOCATION = "9-5 Great Ball of Ire Location"
    HORSEPOWER_ITEM = "1-3 Horsepower Item"
    HORSEPOWER_LOCATION = "1-3 Horsepower Location"
    INFERNO_ITEM = "8-1 Inferno Item"
    INFERNO_LOCATION = "8-1 Inferno Location"
    ITS_A_DRY_HEAT_ITEM = "7-4 It's A Dry Heat Item"
    ITS_A_DRY_HEAT_LOCATION = "7-4 It's A Dry Heat Location"
    I_LOVE_CARATS_ITEM = "9-4 I Love Carats Item"
    I_LOVE_CARATS_LOCATION = "9-4 I Love Carats Location"
    JELLY_JEOPARDY_ITEM = "11-1 Jelly Jeopardy Item"
    JELLY_JEOPARDY_LOCATION = "11-1 Jelly Jeopardy Location"
    JUMP_THE_SQUID_ITEM = "4-4 Jump The Squid Item"
    JUMP_THE_SQUID_LOCATION = "4-4 Jump The Squid Location"
    JUST_DESSERTS_ITEM = "1-4 Just Desserts Item"
    JUST_DESSERTS_LOCATION = "1-4 Just Desserts Location"
    LAST_BALL_ITEM = "5-3 Last Ball Item"
    LAST_BALL_LOCATION = "5-3 Last Ball Location"
    LETTING_OFF_STEAM_ITEM = "8-5 Letting Off Steam Item"
    LETTING_OFF_STEAM_LOCATION = "8-5 Letting Off Steam Location"
    LEVEL_CLEAR_LOCATION = "Level Clear Location"
    LEVEL_UNLOCK_ITEM = "Level Unlock Item"
    LOLLY_DROP_ITEM = "14-1 Lolly Drop Item"
    LOLLY_DROP_LOCATION = "14-1 Lolly Drop Location"
    MAGIC_HOUR_ITEM = "14-3 Magic Hour Item"
    MAGIC_HOUR_LOCATION = "14-3 Magic Hour Location"
    MANY_MINARETS_ITEM = "7-3 Many Minarets Item"
    MANY_MINARETS_LOCATION = "7-3 Many Minarets Location"
    ME_YOWWWW_ITEM = "4-3 Me-Yowwww! Item"
    ME_YOWWWW_LOCATION = "4-3 Me-Yowwww! Location"
    NOOOOO_ITEM = "3-3 Nooooo!!! Item"
    NOOOOO_LOCATION = "3-3 Nooooo!!! Location"
    NOWHERE_STAIRS_ITEM = "3-5 Nowhere Stairs Item"
    NOWHERE_STAIRS_LOCATION = "3-5 Nowhere Stairs Location"
    OLD_FRIENDS_ITEM = "6-4 Old Friends Item"
    OLD_FRIENDS_LOCATION = "6-4 Old Friends Location"
    ORANGE_PEG_COMBO_LOCATION = "Orange Peg Combo Location"
    OUROBOROS_ITEM = "11-2 Ouroboros Item"
    OUROBOROS_LOCATION = "11-2 Ouroboros Location"
    PARADE_ITEM = "4-2 Parade! Item"
    PARADE_LOCATION = "4-2 Parade! Location"
    PEG_COMBO_LOCATION = "Peg Combo Location"
    PERFECTIFIED_ITEM = "5-5 Perfectified Item"
    PERFECTIFIED_LOCATION = "5-5 Perfectified Location"
    PICK_ONE_ITEM = "10-1 Pick One Item"
    PICK_ONE_LOCATION = "10-1 Pick One Location"
    PLANTS_V_ZOMBIES_ITEM = "13-1 Plants v. Zombies Item"
    PLANTS_V_ZOMBIES_LOCATION = "13-1 Plants v. Zombies Location"
    POLLUTION_PICNIC_ITEM = "6-1 Pollution Picnic Item"
    POLLUTION_PICNIC_LOCATION = "6-1 Pollution Picnic Location"
    PROGRESSIVE_ITEM = "Progressive Item"
    PSYCLONE_ITEM = "12-1 Psyclone Item"
    PSYCLONE_LOCATION = "12-1 Psyclone Location"
    SCARY_NIGHT_ITEM = "3-1 Scary Night Item"
    SCARY_NIGHT_LOCATION = "3-1 Scary Night Location"
    SCORE_LOCATION = "Score Location"
    SEASICK_ITEM = "3-2 Seasick Item"
    SEASICK_LOCATION = "3-2 Seasick Location"
    SHADOWSHINE_ITEM = "12-5 Shadowshine Item"
    SHADOWSHINE_LOCATION = "12-5 Shadowshine Location"
    SMARTINESS_ITEM = "2-5 Smartiness Item"
    SMARTINESS_LOCATION = "2-5 Smartiness Location"
    SPAINT_ITEM = "13-3 Spaint! Item"
    SPAINT_LOCATION = "13-3 Spaint! Location"
    STEPPIN_OUT_ITEM = "8-3 Steppin' Out Item"
    STEPPIN_OUT_LOCATION = "8-3 Steppin' Out Location"
    STEP_RIGHT_UP_ITEM = "4-1 Step Right Up Item"
    STEP_RIGHT_UP_LOCATION = "4-1 Step Right Up Location"
    STYLE_SHOT_LOCATION = "Style Shot Location"
    THE_DEEP_ITEM = "11-3 The Deep Item"
    THE_DEEP_LOCATION = "11-3 The Deep Location"
    THE_GUARDIANS_ITEM = "13-2 The Guardians Item"
    THE_GUARDIANS_LOCATION = "13-2 The Guardians Location"
    THE_HENGE_ITEM = "7-2 The Henge Item"
    THE_HENGE_LOCATION = "7-2 The Henge Location"
    THE_RISING_ITEM = "12-4 The Rising Item"
    THE_RISING_LOCATION = "12-4 The Rising Location"
    TOMB_OF_DOOM_ITEM = "9-3 Tomb Of Doom Item"
    TOMB_OF_DOOM_LOCATION = "9-3 Tomb Of Doom Location"
    TO_THE_LIMIT_ITEM = "13-4 To The Limit Item"
    TO_THE_LIMIT_LOCATION = "13-4 To The Limit Location"
    TULIP_LEAVES_ITEM = "14-4 Tulip Leaves Item"
    TULIP_LEAVES_LOCATION = "14-4 Tulip Leaves Location"
    TURN_IT_TO_ZEN_ITEM = "10-2 Turn It To Zen Item"
    TURN_IT_TO_ZEN_LOCATION = "10-2 Turn It To Zen Location"
    TWITCHING_HOUR_ITEM = "3-4 Twitching Hour Item"
    TWITCHING_HOUR_LOCATION = "3-4 Twitching Hour Location"
    USEFUL_ITEM = "Useful Item"
    VAST_VISITOR_ITEM = "6-2 Vast Visitor Item"
    VAST_VISITOR_LOCATION = "6-2 Vast Visitor Location"
    WALL_FLOWER_ITEM = "7-5 Wall Flower Item"
    WALL_FLOWER_LOCATION = "7-5 Wall Flower Location"
    WATER_WHIRLED_ITEM = "11-4 Water Whirled Item"
    WATER_WHIRLED_LOCATION = "11-4 Water Whirled Location"
    WATER_WINGS_ITEM = "8-2 Water Wings Item"
    WATER_WINGS_LOCATION = "8-2 Water Wings Location"
    WE_WILL_ROCK_YOU_ITEM = "10-4 We Will Rock You Item"
    WE_WILL_ROCK_YOU_LOCATION = "10-4 We Will Rock You Location"
    WHY_YOU_BUGGIN_ITEM = "12-2 Why You Buggin'? Item"
    WHY_YOU_BUGGIN_LOCATION = "12-2 Why You Buggin'? Location"
    WILD_THING_ITEM = "10-3 Wild Thing Item"
    WILD_THING_LOCATION = "10-3 Wild Thing Location"
    WYRM_SIGN_ITEM = "12-3 Wyrm Sign Item"
    WYRM_SIGN_LOCATION = "12-3 Wyrm Sign Location"
    X_MARKS_THE_LOOT_ITEM = "9-1 X Marks The Loot Item"
    X_MARKS_THE_LOOT_LOCATION = "9-1 X Marks The Loot Location"


class PeggleNightsAPUsefulItems(enum.Enum):
    FEVER_METER_BONUS = "Fever Meter Permanent Bonus"
    FULL_CLEAR_DISCOUNT = "Full Clear Discount"
    SCORE_MULTIPLIER = "Score Multiplier"
    TARGET_SCORE_DISCOUNT = "Target Score Discount"


class PeggleNightsCharacters(enum.Enum):
    BJORN = "Bjorn"
    JIMMY_LIGHTNING = "Jimmy Lightning"
    KAT_TUT = "Kat Tut"
    SPLORK = "Splork"
    CLAUDE = "Claude"
    RENFIELD = "Renfield"
    TULA = "Tula"
    WARREN = "Warren"
    LORD_CINDERBOTTOM = "Lord Cinderbottom"
    MASTER_HU = "Master Hu"
    MARINA = "Marina"


class PeggleNightsContexts(enum.Enum):
    INVALID = 0
    VALID = 1


class PeggleNightsGameModes(enum.Enum):
    OTHER = 0
    ADVENTURE = 1
    QUICK_PLAY = 2
    DUEL = 3
    CHALLENGE = 4


class PeggleNightsLevels(enum.Enum):
    CRIMEWAVE = "1-1 Crimewave"
    CALL_FOR_HELP = "1-2 Call For Help"
    HORSEPOWER = "1-3 Horsepower"
    JUST_DESSERTS = "1-4 Just Desserts"
    BJORN_IDENTITY = "1-5 Bjorn Identity"
    EXPERIMENT_X = "2-1 Experiment X"
    BRRRZAP = "2-2 Brrrzap!"
    ANTITOXIC = "2-3 Antitoxic"
    BREAKTHROUGH = "2-4 Breakthrough"
    SMARTINESS = "2-5 Smartiness"
    SCARY_NIGHT = "3-1 Scary Night"
    SEASICK = "3-2 Seasick"
    NOOOOO = "3-3 Nooooo!!!"
    TWITCHING_HOUR = "3-4 Twitching Hour"
    NOWHERE_STAIRS = "3-5 Nowhere Stairs"
    STEP_RIGHT_UP = "4-1 Step Right Up"
    PARADE = "4-2 Parade!"
    ME_YOWWWW = "4-3 Me-Yowwww!"
    JUMP_THE_SQUID = "4-4 Jump The Squid"
    DEATH_DEFYING = "4-5 Death Defying"
    BOWL_OF_DROME = "5-1 Bowl Of Drome"
    ARRIVANCE = "5-2 Arrivance"
    LAST_BALL = "5-3 Last Ball"
    EXPLODIOUS = "5-4 Explodious"
    PERFECTIFIED = "5-5 Perfectified"
    POLLUTION_PICNIC = "6-1 Pollution Picnic"
    VAST_VISITOR = "6-2 Vast Visitor"
    EIFFEL_POWER = "6-3 Eiffel Power"
    OLD_FRIENDS = "6-4 Old Friends"
    AU_REVOIR = "6-5 Au Revoir"
    FOUNDING_FATHERS = "7-1 Founding Fathers"
    THE_HENGE = "7-2 The Henge"
    MANY_MINARETS = "7-3 Many Minarets"
    ITS_A_DRY_HEAT = "7-4 It's A Dry Heat"
    WALL_FLOWER = "7-5 Wall Flower"
    INFERNO = "8-1 Inferno"
    WATER_WINGS = "8-2 Water Wings"
    STEPPIN_OUT = "8-3 Steppin' Out"
    FIRE_EATER = "8-4 Fire Eater"
    LETTING_OFF_STEAM = "8-5 Letting Off Steam"
    X_MARKS_THE_LOOT = "9-1 X Marks The Loot"
    BEATS_DRIVING = "9-2 Beats Driving"
    TOMB_OF_DOOM = "9-3 Tomb Of Doom"
    I_LOVE_CARATS = "9-4 I Love Carats"
    GREAT_BALL_OF_IRE = "9-5 Great Ball of Ire"
    PICK_ONE = "10-1 Pick One"
    TURN_IT_TO_ZEN = "10-2 Turn It To Zen"
    WILD_THING = "10-3 Wild Thing"
    WE_WILL_ROCK_YOU = "10-4 We Will Rock You"
    FEEL_THE_NOIZE = "10-5 Feel The Noize"
    JELLY_JEOPARDY = "11-1 Jelly Jeopardy"
    OUROBOROS = "11-2 Ouroboros"
    THE_DEEP = "11-3 The Deep"
    WATER_WHIRLED = "11-4 Water Whirled"
    DIPLOMA_SEE = "11-5 Diploma, See?"
    PSYCLONE = "12-1 Psyclone"
    WHY_YOU_BUGGIN = "12-2 Why You Buggin'?"
    WYRM_SIGN = "12-3 Wyrm Sign"
    THE_RISING = "12-4 The Rising"
    SHADOWSHINE = "12-5 Shadowshine"
    PLANTS_V_ZOMBIES = "13-1 Plants v. Zombies"
    THE_GUARDIANS = "13-2 The Guardians"
    SPAINT = "13-3 Spaint!"
    TO_THE_LIMIT = "13-4 To The Limit"
    BLUE_SLOUGH = "13-5 Blue Slough"
    LOLLY_DROP = "14-1 Lolly Drop"
    BLOOMIN = "14-2 Bloomin'"
    MAGIC_HOUR = "14-3 Magic Hour"
    TULIP_LEAVES = "14-4 Tulip Leaves"
    FLUFFY_SUNNIES = "14-5 Fluffy Sunnies"


class PeggleNightsLevelStates(enum.Enum):
    OTHER = 0
    BEFORE_SHOT = 1
    SHOT_ACTIVE = 2
    AFTER_SHOT = 3
    CHARACTER_SELECT = 9
