import enum


class RivenAPGoals(enum.Enum):
    GOOD_ENDING = 0
    STAR_FISSURE = 1


class RivenAPStartingMovementSpeeds(enum.Enum):
    SLOWER = 0
    VANILLA = 1
    FASTER = 2


class RivenAPStartingRoutes(enum.Enum):
    TEMPLE_GOLDEN_DOME = "Temple -> Golden Dome"
    STARRY_PRISON = "Starry Expanse -> Prison Island Dome"


class RivenAPTags(enum.Enum):
    AGE_233_LOCATION = "Age 233 Location"
    AGE_OF_TAY_LOCATION = "Age of Tay Location"
    BOILER_ITEM = "Boiler Island Item"
    BOILER_LOCATION = "Boiler Island Location"
    CORE_LOCATION = "Core Location"
    FILLER_ITEM = "Filler Item"
    JUNGLE_ITEM = "Jungle Island Item"
    JUNGLE_LOCATION = "Jungle Island Location"
    MAGLEV_ITEM = "Maglev Item"
    PRISON_ITEM = "Prison Island Item"
    PRISON_LOCATION = "Prison Island Location"
    SOLUTION_ITEM = "Puzzle Solution Item"
    STARRY_ITEM = "Starry Expanse Item"
    STARRY_LOCATION = "Starry Expanse Location"
    SURVEY_ITEM = "Survey Island Item"
    SURVEY_LOCATION = "Survey Island Location"
    TEMPLE_ITEM = "Temple Island Item"
    TEMPLE_LOCATION = "Temple Island Location"
    TRAP_ITEM = "Trap Item"
    UNLOCK_ITEM = "Unlock Item"
    USEFUL_ITEM = "Useful Item"


class RivenAPTrapTypes(enum.Enum):
    BLACK_AND_WHITE = "Black and White Trap"
    BLOOM = "Bloom Trap"
    CHROMATIC = "Chromatic Trap"
    COLOR_INVERSION = "Color Inversion Trap"
    MOBILE_GAME = "Mobile Game Trap"
    SLOW = "Slow Trap"
    TUNNEL_VISION = "Tunnel Vision Trap"


class RivenItems(enum.Enum):
    # Temple Island
    TEMPLE_GATE_ROOM_BUTTONS = "TI - Gate Room - Buttons Unlocked"
    TEMPLE_GATE_ROOM_BEETLE_VIEWERS = "TI - Gate Room - Beetle Viewers Unlocked"
    TEMPLE_GATE_ROOM_GATE_GOLDEN_DOME = "TI - Gate Room - Gate to the Golden Dome Opened"
    TEMPLE_GATE_ROOM_GATE_SPINNING_DOME = "TI - Gate Room - Gate to the Spinning Dome Opened"  # Always Precollected
    TEMPLE_STEAM_CONTROL_STEAM_VALVE_LEVER = "TI - Steam Control Room - Steam Valve Lever Unlocked"
    TEMPLE_PROJECTION_ROOM_DOOR = "TI - Projection Room - Door Unlocked"
    TEMPLE_TEMPLE_MAIN_DOOR = "TI - Temple - Main Door Unlocked"
    # Jungle Island
    JUNGLE_VILLAGE_UPPER_DRAWBRIDGE = "JI - Village - Upper Drawbridge Lowered"
    JUNGLE_VILLAGE_PODIUM_PLATFORM = "JI - Village - Podium Platform Extended"
    JUNGLE_VILLAGE_LOWER_DRAWBRIDGE = "JI - Village - Lower Drawbridge Lowered"
    JUNGLE_VILLAGE_SCHOOLHOUSE_DOOR = "JI - Village - Schoolhouse Door Unlocked"
    JUNGLE_WOODCART_PLATFORM_WOODCART_LEVERS = "JI / BI - Woodcart Platforms - Woodcart Levers Unlocked"
    JUNGLE_BLUE_CAVE_BOLU_STICKS = "JI - Blue Cave - Bolu Sticks Enabled"
    JUNGLE_JUNGLE_MAIN_DOOR = "JI - Jungle - Main Door Unlocked"
    JUNGLE_JUNGLE_SIDE_DOOR = "JI - Jungle - Side Door Unlocked"
    JUNGLE_JUNGLE_WAHRK_ELEVATOR_LEVER = "JI - Jungle - Wahrk Elevator Lever Unlocked"
    JUNGLE_JUNGLE_BONE_THRONE_DOOR = "JI - Jungle - Bone Throne Door Unlocked"
    JUNGLE_SUBMARINE_CAVE_BOARDING_PLATFORM_LEVER = "JI - Submarine Cave - Boarding Platform Lever Unlocked"
    JUNGLE_WAHRK_GALLOWS_JAIL_CELL_DOOR_CRANK = "JI - Wahrk Gallows - Jail Cell Door Crank Unlocked"
    JUNGLE_SECRET_MOIETY_TUNNEL_SECRET_DOOR = "JI - Secret Moiety Tunnel - Secret Door Unlocked"
    # Boiler Island
    BOILER_LAKE_STEAM_VALVE_LEVER = "BI - Lake - Steam Valve Lever Unlocked"
    BOILER_BOILER_WATER_VALVE_LEVER = "BI - Boiler - Water Valve Crank Unlocked"  # Technically a lever; looks like a crank
    BOILER_MINING_CAVE_WATER_PUMP_BUTTON = "BI - Mining Cave - Water Pump Button Unlocked"
    BOILER_LAB_ELEVATOR_CRANKS = "BI - Lab - Elevator Cranks Unlocked"
    BOILER_LAB_CATWALK_DOOR = "BI - Lab - Catwalk Door Unlocked"
    BOILER_LAB_MAGLEV_DOOR = "BI - Lab - Maglev Door Unlocked"
    BOILER_LAB_GEODE_CUTTER_CRANK = "BI - Lab - Geode Cutter Crank Unlocked"
    # Survey Island
    SURVEY_PLATEAU_ELEVATOR_BUTTONS = "SI - Plateau - Elevator Buttons Unlocked"
    SURVEY_GEHNS_SPY_ROOM_LEFT_AQUARIUM_CHAIR_LEVER = "SI - Gehn's Spy Room - Left Aquarium Chair Lever Unlocked"
    SURVEY_GEHNS_SPY_ROOM_RIGHT_AQUARIUM_CHAIR_LEVER = "SI - Gehn's Spy Room - Right Aquarium Chair Lever Unlocked"
    SURVEY_UPPER_PLATEAU_GEHNTRIS_BOARD = "SI - Upper Plateau - Gehntris Board Unlocked"
    SURVEY_MAGLEV_PLATFORM_TO_BOILER_DOOR_LEVER = "SI - Maglev Platform to Boiler - Door Lever Unlocked"
    # Prison Island
    PRISON_BEACH_LOG_TELESCOPE = "PI - Beach - Log Telescope Unlocked"
    # Starry Expanse
    STARRY_MARBLE_DEVICES = "SE - Marble Devices Unlocked"
    STARRY_JUNGLE_BRIDGE = "SE - Jungle Bridge Extended"
    STARRY_BOILER_BRIDGE = "SE - Boiler Bridge Extended"
    STARRY_SURVEY_BRIDGE = "SE - Survey Bridge Extended"
    STARRY_PRISON_BRIDGE = "SE - Prison Bridge Extended"
    # Maglevs
    MAGLEV_TEMPLE_JUNGLE_THROTTLE_LEVER = "Maglev (TI <-> JI) - Throttle Lever Unlocked"
    MAGLEV_BOILER_SURVEY_THROTTLE_LEVER = "Maglev (BI <-> SI) - Throttle Lever Unlocked"
    MAGLEV_SURVEY_JUNGLE_THROTTLE_LEVER = "Maglev (SI <-> JI) - Throttle Lever Unlocked"
    # Puzzle Solutions
    SOLUTION_ANIMAL_CIRCLE = "Puzzle Solution: Animal Circle"
    SOLUTION_PRISON_ELEVATOR = "Puzzle Solution: Prison Elevator"
    SOLUTION_BOLU_STICKS = "Puzzle Solution: Bolu Sticks"
    SOLUTION_GOLDEN_DOME_SLIDERS = "Puzzle Solution: Golden Dome Sliders"
    SOLUTION_STAR_FISSURE_TELESCOPE = "Progressive Puzzle Solution: Star Fissure Telescope"  # 10x - 1 symbol per copy
    # Useful
    MOVEMENT_SPEED = "Progressive Movement Speed"
    # Traps
    TRAP_BLACK_AND_WHITE = RivenAPTrapTypes.BLACK_AND_WHITE.value
    TRAP_BLOOM = RivenAPTrapTypes.BLOOM.value
    TRAP_CHROMATIC = RivenAPTrapTypes.CHROMATIC.value
    TRAP_COLOR_INVERSION = RivenAPTrapTypes.COLOR_INVERSION.value
    TRAP_MOBILE_GAME = RivenAPTrapTypes.MOBILE_GAME.value
    TRAP_SLOW = RivenAPTrapTypes.SLOW.value
    TRAP_TUNNEL_VISION = RivenAPTrapTypes.TUNNEL_VISION.value
    # Filler
    VIAL_OF_WAHRK_GALL_INK = "Vial of Wahrk Gall-Ink"
    SLIVER_OF_FIRE_MARBLE_GLASS = "Sliver of Fire-Marble Glass"
    FRACTURED_MAGLEV_FUSE = "Fractured Maglev Fuse"
    MOIETY_DART_TIP_RESIN = "Moiety Dart-Tip Resin"
    SCRAP_BOOK_BINDING_LEATHER = "Scrap Book-Binding Leather"
    CORRODED_BOILER_PRESSURE_GAUGE = "Corroded Boiler Pressure Gauge"
    CARVED_REBEL_DAGGER = "Carved Rebel Dagger"
    GEHNS_FAILED_AGE_SURVEY_NOTES = "Gehn's Failed Age Survey Notes"
    POLISHED_SUNNER_BONE_NEEDLE = "Polished Sunner-Bone Needle"
    TARNISHED_SURVEY_SCOPE_LENS = "Tarnished Survey-Scope Lens"


class RivenLocations(enum.Enum):
    # Temple Island
    TEMPLE_PLATEAU_READ_ATRUS_JOURNAL = "Read Atrus's Journal"  # Is first available in TI - Plateau; can be done anywhere
    TEMPLE_PLATEAU_GAZE_STAR_FISSURE = "TI - Plateau - Gaze at the Star Fissure"
    TEMPLE_PLATEAU_BREAK_TELESCOPE_LEVER = "TI - Plateau - Break the Telescope Lever"
    TEMPLE_PLATEAU_FIND_CHO = "TI - Plateau - Find Out Where Cho Went"
    TEMPLE_PLATEAU_REMOVE_HINGE = "TI - Side Gate - Remove the Hinge"
    TEMPLE_GATE_ROOM_BEETLE_1 = "TI - Gate Room - Look Through the First Beetle"
    TEMPLE_GATE_ROOM_BEETLE_2 = "TI - Gate Room - Look Through the Second Beetle"
    TEMPLE_GATE_ROOM_BEETLE_3 = "TI - Gate Room - Look Through the Third Beetle"
    TEMPLE_GATE_ROOM_BEETLE_4 = "TI - Gate Room - Look Through the Fourth Beetle"
    TEMPLE_GATE_ROOM_BEETLE_5 = "TI - Gate Room - Look Through the Fifth Beetle"
    TEMPLE_STEAM_CONTROL_ROOM_POWER_TELESCOPE = "TI - Steam Control Room - Power the Telescope"
    TEMPLE_SPINNING_DOME_OPEN_DOME = "TI - Spinning Dome - Open the Dome"
    TEMPLE_GOLDEN_DOME_ENTER_DOME = "TI - Golden Dome - Enter the Dome"
    TEMPLE_GOLDEN_DOME_TEMPLE_SYMBOL = "TI - Golden Dome - Look at Temple Island Symbol"
    TEMPLE_GOLDEN_DOME_JUNGLE_SYMBOL = "TI - Golden Dome - Look at Jungle Island Symbol"
    TEMPLE_GOLDEN_DOME_BOILER_SYMBOL = "TI - Golden Dome - Look at Boiler Island Symbol"
    TEMPLE_GOLDEN_DOME_SURVEY_SYMBOL = "TI - Golden Dome - Look at Survey Island Symbol"
    TEMPLE_GOLDEN_DOME_PRISON_SYMBOL = "TI - Golden Dome - Look at Prison Island Symbol"
    TEMPLE_PROJECTION_ROOM_ENTER_PROJECTION_ROOM = "TI - Outside Golden Dome - Enter the Projection Room"
    TEMPLE_PROJECTION_ROOM_SPIDER_CHAIR = "TI - Projection Room - Sit in the Spider Chair"
    TEMPLE_GOLDEN_DOME_COLLAPSE_BRIDGE = "TI - Outside Golden Dome - Collapse the Bridge"
    TEMPLE_GOLDEN_DOME_UPPER_ACCESS_UPPER = "TI - Golden Dome - Access the Upper Level"
    TEMPLE_GOLDEN_DOME_UPPER_PLACE_PURPLE_MARBLE = "TI - Golden Dome Upper Level - Place the Purple Marble"
    TEMPLE_GOLDEN_DOME_UPPER_PLACE_GREEN_MARBLE = "TI - Golden Dome Upper Level - Place the Green Marble"
    TEMPLE_GOLDEN_DOME_UPPER_PLACE_BLUE_MARBLE = "TI - Golden Dome Upper Level - Place the Blue Marble"
    TEMPLE_GOLDEN_DOME_UPPER_PLACE_RED_MARBLE = "TI - Golden Dome Upper Level - Place the Red Marble"
    TEMPLE_GOLDEN_DOME_UPPER_PLACE_ORANGE_MARBLE = "TI - Golden Dome Upper Level - Place the Orange Marble"
    TEMPLE_GOLDEN_DOME_UPPER_ACCESS_AGE_233_BOOK = "TI - Golden Dome Upper Level - Gain Access to the Age 233 Book"
    TEMPLE_MAGLEV_PLATFORM_TO_JUNGLE_PRESS_BUTTON = "TI - Maglev Platform - Press the Button"
    # Jungle Island
    JUNGLE_VISIT_VISIT_JUNGLE = "JI - Visit Jungle Island"
    JUNGLE_MAGLEV_PLATFORM_TO_TEMPLE_PRESS_BUTTON = "JI - Maglev Platform (Temple) - Press the Button"
    JUNGLE_WAHRK_TOTEM_INTERACT = "JI - Wahrk Totem - Interact with the Totem"
    JUNGLE_WAHRK_TOTEM_DIVERT_WATER = "JI - Wahrk Totem - Divert the Water"
    JUNGLE_BEACH_COLLECT_MOIETY_LENS = "JI - Beach - Collect the Moiety Lens"
    JUNGLE_BEETLE_TOTEM_INTERACT = "JI - Beetle Totem - Interact with the Totem"
    JUNGLE_OUTSIDE_VILLAGE_SCHOOL_SIDE_GRAB_BBQ = "JI - Outside Village (Schoolhouse Side) - Grab Some BBQ"
    JUNGLE_SCHOOLHOUSE_ENTER_SCHOOLHOUSE = "JI - Outside Village (Schoolhouse Side) - Enter the Schoolhouse"
    JUNGLE_SCHOOLHOUSE_INSPECT_WAHRK_GAME = "JI - Schoolhouse - Inspect the Wahrk Game"
    JUNGLE_VILLAGE_KNOCK_ON_DOOR = "JI - Village - Knock on the Door"
    JUNGLE_VILLAGE_INHALE_STEAM = "JI - Village - Inhale Some Steam"
    JUNGLE_VILLAGE_SHUT_STEAM_VENT = "JI - Village - Shut the Steam Vent"
    JUNGLE_VILLAGE_PROVIDE_WATER_TO_TREE = "JI - Village - Provide Water to the Tree"
    JUNGLE_BLUE_CAVE_OPEN_SECRET_DOOR = "JI - Blue Cave - Open the Secret Door"
    JUNGLE_LOGGING_AREA_GET_SPOTTED_BY_GUARD = "JI - Before Blue Cave - Get Spotted by the Guard"
    JUNGLE_YTRAM_TOTEM_INTERACT = "JI - Ytram Totem - Interact with the Totem"
    JUNGLE_WOODCART_PLATFORM_PRESS_BUTTON = "JI - Woodcart Platform - Press the Button"
    JUNGLE_WAHRK_ELEVATOR_OPEN_WAHRKS_MOUTH = "JI - Wahrk Elevator - Open the Wahrk's Mouth"
    JUNGLE_JUNGLE_CATWALKS_OPEN_DOME = "JI - Spinning Dome - Open the Dome"
    JUNGLE_BONE_THRONE_LOOK_DOWN_UPON_VILLAGE = "JI - Bone Throne - Look Down Upon the Village"
    JUNGLE_BONE_THRONE_SEAL_WAHRK_GALLOWS = "JI - Bone Throne - Seal the Wahrk Gallows"
    JUNGLE_MAGLEV_PLATFORM_TO_SURVEY_PRESS_BUTTON = "JI - Maglev Platform (Survey) - Press the Button"
    JUNGLE_MAGLEV_PLATFORM_TO_SURVEY_PRESS_OTHER_BUTTON = "JI - Maglev Platform (Survey) - Press the Other Button"
    JUNGLE_SUBMARINE_CAVE_PRESS_BUTTON = "JI - Submarine Cave - Press the Button"
    JUNGLE_SUBMARINE_DESTINATION_SUBMARINE_CAVE_BOARD_SUBMARINE = "JI - Submarine Cave - Board the Submarine"
    JUNGLE_SUBMARINE_DESTINATION_VILLAGE_PILOT = "JI - Submarine - Pilot to the Village"
    JUNGLE_VILLAGE_WATER_HOLE_FLICK_SWITCH = "JI - Village Water Hole - Flick the Switch"
    JUNGLE_INSECT_TOTEM_INTERACT = "JI - Insect Totem - Interact with the Totem"
    JUNGLE_SUBMARINE_DESTINATION_PODIUM_PILOT = "JI - Submarine - Pilot to the Podium"
    JUNGLE_SUBMARINE_DESTINATION_SCHOOLHOUSE_PILOT = "JI - Submarine - Pilot to the Schoolhouse"
    JUNGLE_SUBMARINE_DESTINATION_WAHRK_GALLOWS_PILOT = "JI - Submarine - Pilot to the Wahrk Gallows"
    JUNGLE_WAHRK_GALLOWS_JAIL_CELL_OPEN_SECRET_DOOR = "JI - Wahrk Gallows Jail Cell - Open the Secret Door"
    JUNGLE_SECRET_MOIETY_TUNNEL_TURN_ON_LIGHT_1 = "JI - Secret Moiety Tunnel - Turn On the First Paddle Light"
    JUNGLE_SECRET_MOIETY_TUNNEL_TURN_ON_LIGHT_2 = "JI - Secret Moiety Tunnel - Turn On the Second Paddle Light"
    JUNGLE_SECRET_MOIETY_TUNNEL_TURN_ON_LIGHT_3 = "JI - Secret Moiety Tunnel - Turn On the Third Paddle Light"
    JUNGLE_SECRET_MOIETY_TUNNEL_TURN_ON_LIGHT_4 = "JI - Secret Moiety Tunnel - Turn On the Fourth Paddle Light"
    JUNGLE_SECRET_MOIETY_TUNNEL_TURN_ON_LIGHT_5 = "JI - Secret Moiety Tunnel - Turn On the Fifth Paddle Light"
    JUNGLE_SECRET_MOIETY_TUNNEL_TURN_ON_LIGHT_6 = "JI - Secret Moiety Tunnel - Turn On the Sixth Paddle Light"
    JUNGLE_SECRET_MOIETY_TUNNEL_TURN_ON_LIGHT_7 = "JI - Secret Moiety Tunnel - Turn On the Seventh Paddle Light"
    JUNGLE_SECRET_MOIETY_TUNNEL_TURN_ON_LIGHT_8 = "JI - Secret Moiety Tunnel - Turn On the Eighth Paddle Light"
    JUNGLE_SECRET_MOIETY_TUNNEL_OPEN_SECRET_DOOR = "JI - Secret Moiety Tunnel - Open the Secret Door"
    JUNGLE_ANIMAL_CIRCLE_ROOM_ACCESS_TAY_BOOK = "JI - Animal Circle Room - Gain Access to the Age of Tay Book"
    JUNGLE_ANIMAL_CIRCLE_ROOM_INPUT_CLASSIC_SOLUTION = "JI - Animal Circle Room - Recall a Specific Moiety Code"
    # Boiler Island
    BOILER_VISIT_VISIT_BOILER = "BI - Visit Boiler Island"
    BOILER_WOODCART_PLATFORM_PRESS_BUTTON = "BI - Woodcart Platform - Press the Button"
    BOILER_WOODCART_PLATFORM_TURN_ON_WOOD_CHIPPER = "BI - Woodcart Platform - Turn On the Wood Chipper"
    BOILER_LAKE_DIRECT_STEAM_WOOD_CHIPPER = "BI - Lake - Direct the Steam to the Wood Chipper"
    BOILER_LAKE_DIRECT_STEAM_BOILER = "BI - Lake - Direct the Steam to the Boiler"
    BOILER_LAKE_DISCOVER_BURNT_BOOK = "BI - Furnace - Discover the Burnt Book"
    BOILER_BOILER_CONTROLS_RAISE_FLOOR = "BI - Boiler Controls - Raise the Floor"
    BOILER_BOILER_CONTROLS_DRAIN_WATER = "BI - Boiler Controls - Drain the Water"
    BOILER_BOILER_CONTROLS_TURN_OFF_HEAT = "BI - Boiler Controls - Turn Off the Heat"
    BOILER_INSIDE_BOILER_ENTER_BOILER = "BI - Boiler - Enter the Boiler"
    BOILER_BALCONY_OPEN_HATCH = "BI - Balcony - Open the Hatch"
    BOILER_SPINNING_DOME_OPEN_DOME = "BI - Spinning Dome - Open the Dome"
    BOILER_MINING_CAVE_PUMP_SIDE_DRAIN_WATER = "BI - Mining Cave - Drain the Water"
    BOILER_MINING_CAVE_PUMP_SIDE_MINE_FIRE_MARBLE_GEODE = "BI - Mining Cave - Mine a Fire Marble Geode"
    BOILER_MINING_CAVE_ELEVATOR_SIDE_SLOT_CART_IN_ELEVATOR = "BI - Mining Cave - Slot the Cart in the Elevator"
    BOILER_LAB_VISIT_GEHNS_LAB = "BI - Lab - Visit Gehn's Lab"
    BOILER_LAB_READ_GEHNS_JOURNAL = "BI - Lab - Read Gehn's Journal"
    BOILER_LAB_TRY_OUT_MAGNIFYING_GLASS = "BI - Lab - Try Out the Magnifying Glass"
    BOILER_LAB_CLOSE_PRESS = "BI - Lab - Close the Press"
    BOILER_LAB_CRACK_OPEN_FIRE_MARBLE_GEODE = "BI - Lab - Crack Open the Fire Marble Geode"
    BOILER_LAB_MEASURE_OPTIMAL_MARBLE_STRIKE_FORCE = "BI - Lab - Measure the Optimal Marble Strike Force"
    BOILER_LAB_FREE_YTRAM = "BI - Lab - Free the Ytram"
    BOILER_LAB_SPEED_UP_FLYWHEEL = "BI - Lab - Speed Up the Flywheel"
    BOILER_LAB_STOP_POLISHER = "BI - Lab - Stop the Polisher"
    BOILER_MAGLEV_PLATFORM_TO_SURVEY_PRESS_BUTTON = "BI - Maglev Platform (Survey) - Press the Button"
    # Survey Island
    SURVEY_VISIT_VISIT_SURVEY = "SI - Visit Survey Island"
    SURVEY_MAGLEV_PLATFORM_TO_BOILER_PRESS_BUTTON = "SI - Maglev Platform (Boiler) - Press the Button"
    SURVEY_MAGLEV_PLATFORM_TO_BOILER_PRESS_OTHER_BUTTON = "SI - Maglev Platform (Boiler) - Press the Other Button"
    SURVEY_GEHNS_SPY_ROOM_DISCOVER_GEHNS_SPY_ROOM = "SI - Plateau Elevator - Discover Gehn's Spy Room"
    SURVEY_GEHNS_SPY_ROOM_VIEW_PRISON_CAMERA = "SI - Gehn's Spy Room - View the Prison Island Camera"
    SURVEY_GEHNS_SPY_ROOM_VIEW_JUNGLE_CAMERA = "SI - Gehn's Spy Room - View the Jungle Island Camera"
    SURVEY_GEHNS_SPY_ROOM_VIEW_SURVEY_CAMERA = "SI - Gehn's Spy Room - View the Survey Island Camera"
    SURVEY_GEHNS_SPY_ROOM_VIEW_BOILER_CAMERA = "SI - Gehn's Spy Room - View the Boiler Island Camera"
    SURVEY_GEHNS_SPY_ROOM_VIEW_TEMPLE_CAMERA = "SI - Gehn's Spy Room - View the Temple Island Camera"
    SURVEY_GEHNS_SPY_ROOM_TURN_ON_BLUE_LIGHT = "SI - Gehn's Spy Room - Turn On the Blue Light"
    SURVEY_GEHNS_SPY_ROOM_TURN_ON_GREEN_LIGHT = "SI - Gehn's Spy Room - Turn On the Green Light"
    SURVEY_GEHNS_SPY_ROOM_TURN_ON_YELLOW_LIGHT = "SI - Gehn's Spy Room - Turn On the Yellow Light"
    SURVEY_GEHNS_SPY_ROOM_TURN_ON_ORANGE_LIGHT = "SI - Gehn's Spy Room - Turn On the Orange Light"
    SURVEY_GEHNS_SPY_ROOM_TURN_ON_RED_LIGHT = "SI - Gehn's Spy Room - Turn On the Red Light"
    SURVEY_GEHNS_SPY_ROOM_ANNOY_WAHRK = "SI - Gehn's Spy Room - Annoy the Wahrk"
    SURVEY_UPPER_PLATEAU_OPEN_DOME = "SI - Spinning Dome - Open the Dome"
    SURVEY_UPPER_PLATEAU_PRESS_GEHNTRIS_TEMPLE_BUTTON = "SI - Upper Plateau - Press the Gehntris Temple Button"
    SURVEY_UPPER_PLATEAU_PRESS_GEHNTRIS_JUNGLE_BUTTON = "SI - Upper Plateau - Press the Gehntris Jungle Button"
    SURVEY_UPPER_PLATEAU_PRESS_GEHNTRIS_BOILER_BUTTON = "SI - Upper Plateau - Press the Gehntris Boiler Button"
    SURVEY_UPPER_PLATEAU_PRESS_GEHNTRIS_SURVEY_BUTTON = "SI - Upper Plateau - Press the Gehntris Survey Button"
    SURVEY_UPPER_PLATEAU_PRESS_GEHNTRIS_PRISON_BUTTON = "SI - Upper Plateau - Press the Gehntris Prison Button"
    SURVEY_UNDERGROUND_TUNNEL_ENCOUNTER_GEHNS_SCRIBE = "SI - Underground Tunnel - Encounter Gehn's Scribe"
    SURVEY_MAGLEV_PLATFORM_TO_JUNGLE_PRESS_BUTTON = "SI - Maglev Platform (Jungle) - Press the Button"
    # Prison Island
    PRISON_VISIT_VISIT_PRISON = "PI - Visit Prison Island"
    PRISON_SPINNING_DOME_OPEN_DOME = "PI - Spinning Dome - Open the Dome"
    PRISON_BEACH_INTERACT_TOTEM = "PI - Fish Totem - Interact with the Totem"
    PRISON_BEACH_ROTATE_LOG_TELESCOPE = "PI - Beach - Rotate the Log Telescope"
    PRISON_BEACH_LOOK_THROUGH_LOG_TELESCOPE = "PI - Beach - Look Through the Log Telescope"
    PRISON_OUTSIDE_JAIL_CELL_MEET_CATHERINE = "PI - Outside Jail Cell - Meet Catherine"
    PRISON_JAIL_CELL_FREE_CATHERINE = "PI - Jail Cell - Free Catherine"
    # Age of Tay
    AGE_OF_TAY_GET_IMPRISONED = "TAY - Get Imprisoned"

    AGE_OF_TAY_GET_PRISON_BOOK_BACK = "TAY - Get the Prison Book Back"
    AGE_OF_TAY_READ_CATHERINES_JOURNAL = "Read Catherine's Journal"  # Is first available in TAY; can be done anywhere
    AGE_OF_TAY_EXPLORE_HIVE = "TAY - Explore the Hive"
    # Age 233
    AGE_233_MEET_GEHN = "233 - Meet Gehn"
    AGE_233_TRAP_GEHN = "233 - Trap Gehn"
    AGE_233_TURN_ON_STOVE = "233 - Turn On the Stove"
    AGE_233_LOWER_CAGE = "233 - Lower the Cage"
    AGE_233_GRAB_BBQ = "233 - Grab Some BBQ"
    AGE_233_SIT_ON_THRONE = "233 - Sit on the Throne"
    AGE_233_TURN_ON_FAUCET = "233 - Turn On the Faucet"
    AGE_233_WATCH_KETAS_PROJECTION = "233 - Watch Keta's Projection"
    AGE_233_READ_GEHNS_JOURNAL = "233 - Read Gehn's Journal"
    AGE_233_LEARN_PRISON_ELEVATOR_CODE = "233 - Learn the Prison Elevator Code"
    # Starry Expanse
    STARRY_VISIT_VISIT_STARRY = "SE - Visit the Starry Expanse"
    STARRY_CONTROLS_NAVIGATE_EXPANSE = "SE - Controls - Navigate the Expanse"
    STARRY_TEMPLE_DOME_DELIVER_GREEN_POWER_MARBLE = "SE - Temple Dome - Deliver the Green Power Marble"
    STARRY_JUNGLE_DOME_DELIVER_RED_POWER_MARBLE = "SE - Jungle Dome - Deliver the Red Power Marble"
    STARRY_BOILER_DOME_DELIVER_PURPLE_POWER_MARBLE = "SE - Boiler Dome - Deliver the Purple Power Marble"
    STARRY_SURVEY_DOME_DELIVER_ORANGE_POWER_MARBLE = "SE - Survey Dome - Deliver the Orange Power Marble"
    STARRY_PRISON_DOME_DELIVER_BLUE_POWER_MARBLE = "SE - Prison Dome - Deliver the Blue Power Marble"


class RivenRegions(enum.Enum):
    MENU = "Menu"
    # Temple Island
    TEMPLE_PLATEAU = "Temple Island - Plateau"
    TEMPLE_STAR_FISSURE = "Temple Island - Star Fissure"
    TEMPLE_GATE_ROOM = "Temple Island - Gate Room"
    TEMPLE_STEAM_CONTROL_ROOM = "Temple Island - Steam Control Room"
    TEMPLE_SPINNING_DOME = "Temple Island - Spinning Dome"
    TEMPLE_GOLDEN_DOME = "Temple Island - Golden Dome"
    TEMPLE_PROJECTION_ROOM = "Temple Island - Projection Room"
    TEMPLE_GOLDEN_DOME_UPPER = "Temple Island - Golden Dome - Upper Level"
    TEMPLE_TEMPLE = "Temple Island - Temple"
    TEMPLE_MAGLEV_PLATFORM_TO_JUNGLE = "Temple Island - Maglev Platform (Jungle)"
    # Jungle Island
    JUNGLE_VISIT = "Jungle Island - Visit"
    JUNGLE_MAGLEV_PLATFORM_TO_TEMPLE = "Jungle Island - Maglev Platform (Temple)"
    JUNGLE_WAHRK_TOTEM = "Jungle Island - Wahrk Totem"
    JUNGLE_BEACH = "Jungle Island - Beach"
    JUNGLE_BEETLE_TOTEM = "Jungle Island - Beetle Totem"
    JUNGLE_OUTSIDE_VILLAGE_SCHOOL_SIDE = "Jungle Island - Outside Village - Schoolhouse Side"
    JUNGLE_SCHOOLHOUSE = "Jungle Island - Schoolhouse"
    JUNGLE_VILLAGE = "Jungle Island - Village"
    JUNGLE_VILLAGE_PODIUM = "Jungle Island - Village - Podium"
    JUNGLE_OUTSIDE_VILLAGE_CHIMNEY_SIDE = "Jungle Island - Outside Village - Chimney Side"
    JUNGLE_BLUE_CAVE = "Jungle Island - Blue Cave"
    JUNGLE_LOGGING_AREA = "Jungle Island - Logging Area"
    JUNGLE_YTRAM_TOTEM = "Jungle Island - Ytram Totem"
    JUNGLE_WOODCART_PLATFORM = "Jungle Island - Woodcart Platform"
    JUNGLE_JUNGLE = "Jungle Island - Jungle"
    JUNGLE_WAHRK_ELEVATOR = "Jungle Island - Wahrk Elevator"
    JUNGLE_JUNGLE_CATWALKS = "Jungle Island - Jungle Catwalks"
    JUNGLE_BONE_THRONE = "Jungle Island - Bone Throne"
    JUNGLE_MAGLEV_PLATFORM_TO_SURVEY = "Jungle Island - Maglev Platform (Survey)"
    JUNGLE_SUBMARINE_CAVE = "Jungle Island - Submarine Cave"
    JUNGLE_SUBMARINE_DESTINATION_SUBMARINE_CAVE = "Jungle Island - Submarine Destination - Submarine Cave"
    JUNGLE_SUBMARINE_DESTINATION_VILLAGE = "Jungle Island - Submarine Destination - Village"
    JUNGLE_VILLAGE_WATER_HOLE = "Jungle Island - Village Water Hole"
    JUNGLE_INSECT_TOTEM = "Jungle Island - Insect Totem"
    JUNGLE_SUBMARINE_DESTINATION_PODIUM = "Jungle Island - Submarine Destination - Podium"
    JUNGLE_SUBMARINE_DESTINATION_SCHOOLHOUSE = "Jungle Island - Submarine Destination - Schoolhouse"
    JUNGLE_SUBMARINE_DESTINATION_WAHRK_GALLOWS = "Jungle Island - Submarine Destination - Wahrk Gallows"
    JUNGLE_WAHRK_GALLOWS = "Jungle Island - Wahrk Gallows"
    JUNGLE_WAHRK_GALLOWS_UPPER = "Jungle Island - Wahrk Gallows - Upper Level"
    JUNGLE_WAHRK_GALLOWS_JAIL_CELL = "Jungle Island - Wahrk Gallows - Jail Cell"
    JUNGLE_SECRET_MOIETY_TUNNEL = "Jungle Island - Secret Moiety Tunnel"
    JUNGLE_ANIMAL_CIRCLE_ROOM = "Jungle Island - Animal Circle Room"
    # Boiler Island
    BOILER_VISIT = "Boiler Island - Visit"
    BOILER_WOODCART_PLATFORM = "Boiler Island - Woodcart Platform"
    BOILER_LAKE = "Boiler Island - Lake"
    BOILER_BOILER_CONTROLS = "Boiler Island - Boiler Controls"
    BOILER_INSIDE_BOILER = "Boiler Island - Inside Boiler"
    BOILER_BALCONY = "Boiler Island - Balcony"
    BOILER_SPINNING_DOME = "Boiler Island - Spinning Dome"
    BOILER_MINING_CAVE_PUMP_SIDE = "Boiler Island - Mining Cave - Pump Side"
    BOILER_MINING_CAVE_ELEVATOR_SIDE = "Boiler Island - Mining Cave - Elevator Side"
    BOILER_LAB = "Boiler Island - Lab"
    BOILER_CATWALK = "Boiler Island - Catwalk"
    BOILER_MAGLEV_PLATFORM_TO_SURVEY = "Boiler Island - Maglev Platform (Survey)"
    # Survey Island
    SURVEY_VISIT = "Survey Island - Visit"
    SURVEY_MAGLEV_PLATFORM_TO_BOILER = "Survey Island - Maglev Platform (Boiler)"
    SURVEY_LOWER_PLATEAU = "Survey Island - Lower Plateau"
    SURVEY_PLATEAU_ELEVATOR = "Survey Island - Plateau Elevator"
    SURVEY_GEHNS_SPY_ROOM = "Survey Island - Gehn's Spy Room"
    SURVEY_UPPER_PLATEAU = "Survey Island - Upper Plateau"
    SURVEY_GOLDEN_ELEVATOR_ROOM = "Survey Island - Golden Elevator Room"
    SURVEY_UNDERGROUND_TUNNEL = "Survey Island - Underground Tunnel"
    SURVEY_MAGLEV_PLATFORM_TO_JUNGLE = "Survey Island - Maglev Platform (Jungle)"
    # Prison Island
    PRISON_VISIT = "Prison Island - Visit"
    PRISON_SPINNING_DOME = "Prison Island - Spinning Dome"
    PRISON_BEACH = "Prison Island - Beach"
    PRISON_OUTSIDE_JAIL_CELL = "Prison Island - Outside Jail Cell"
    PRISON_ELEVATOR = "Prison Island - Elevator"
    PRISON_JAIL_CELL = "Prison Island - Jail Cell"
    # Age of Tay
    AGE_OF_TAY = "Age of Tay"
    # Age 233
    AGE_233 = "Age 233"
    # Starry Expanse
    STARRY_VISIT = "Starry Expanse - Visit"
    STARRY_CONTROLS = "Starry Expanse - Controls"
    STARRY_TEMPLE_DOME = "Starry Expanse - Temple Dome"
    STARRY_JUNGLE_DOME = "Starry Expanse - Jungle Dome"
    STARRY_BOILER_DOME = "Starry Expanse - Boiler Dome"
    STARRY_SURVEY_DOME = "Starry Expanse - Survey Dome"
    STARRY_PRISON_DOME = "Starry Expanse - Prison Dome"
