import enum


class SeveredSteelAPGoals(enum.Enum):
    EDENSYS_ROOT_KEYS_FINAL_LEVEL = 0
    EDENSYS_ROOT_KEY_HUNT = 1


class SeveredSteelAPMutatorPoolTypes(enum.Enum):
    ONLY_DEBUFFS = 0
    MOSTLY_DEBUFFS = 1
    BALANCED = 2
    MOSTLY_BUFFS = 3
    ONLY_BUFFS = 4
    OOPS_ALL_TRIPLE_THREAT = 5
    OOPS_ALL_THE_SAME = 6


class SeveredSteelAPRequirementModes(enum.Enum):
    SAME_FOR_ALL = 0
    RANDOM = 1


class SeveredSteelAPTags(enum.Enum):
    APARTMENTS_ITEM = "APARTMENTS Item"
    APARTMENTS_LOCATION = "APARTMENTS Location"
    ARMORY_ITEM = "ARMORY Item"
    ARMORY_LOCATION = "ARMORY Location"
    ART_GALLERY_ITEM = "ART GALLERY Item"
    ART_GALLERY_LOCATION = "ART GALLERY Location"
    BARRACKS_ITEM = "BARRACKS Item"
    BARRACKS_LOCATION = "BARRACKS Location"
    CAFETERIA_ITEM = "CAFETERIA Item"
    CAFETERIA_LOCATION = "CAFETERIA Location"
    CEO_OFFICE_ITEM = "CEO OFFICE Item"
    CEO_OFFICE_LOCATION = "CEO OFFICE Location"
    CHALLENGE_BASE_LOCATION = "Complete 2 Challenges Location"
    CHALLENGE_LOCATION = "Challenge Location"
    CHALLENGE_STYLISH_ACTION_LOCATION = "Complete Stylish Action Challenge Location"
    CHECKPOINT_ITEM = "CHECKPOINT Item"
    CHECKPOINT_LOCATION = "CHECKPOINT Location"
    CIPHER_ITEM = "CIPHER Item"
    CIPHER_LOCATION = "CIPHER Location"
    CITY_ITEM = "CITY Item"
    CITY_LOCATION = "CITY Location"
    CLEAVE_ITEM = "CLEAVE Item"
    CLEAVE_LOCATION = "CLEAVE Location"
    CONSCIENCE_ITEM = "CONSCIENCE Item"
    CONSCIENCE_LOCATION = "CONSCIENCE Location"
    CORRIDOR_ITEM = "CORRIDOR Item"
    CORRIDOR_LOCATION = "CORRIDOR Location"
    COSMOLOGY_ITEM = "COSMOLOGY Item"
    COSMOLOGY_LOCATION = "COSMOLOGY Location"
    CROSS_ITEM = "CROSS Item"
    CROSS_LOCATION = "CROSS Location"
    CYBERMEDICINE_ITEM = "CYBERMEDICINE Item"
    CYBERMEDICINE_LOCATION = "CYBERMEDICINE Location"
    DATA_PRISM_ITEM = "DATA PRISM Item"
    DATA_PRISM_LOCATION = "DATA PRISM Location"
    DOUBLE_SCORE_ITEM = "Double Score Item"
    EPOCH_ITEM = "EPOCH Item"
    EPOCH_LOCATION = "EPOCH Location"
    ESCAPISM_ITEM = "ESCAPISM Item"
    ESCAPISM_LOCATION = "ESCAPISM Location"
    ESTATE_ITEM = "ESTATE Item"
    ESTATE_LOCATION = "ESTATE Location"
    FILLER_ITEM = "Filler Item"
    FLOAT_ITEM = "FLOAT Item"
    FLOAT_LOCATION = "FLOAT Location"
    FOREST_ITEM = "FOREST Item"
    FOREST_LOCATION = "FOREST Location"
    GARDEN_ITEM = "GARDEN Item"
    GARDEN_LOCATION = "GARDEN Location"
    GOAL_ITEM = "Goal Item"
    GREENS_ITEM = "GREENS Item"
    GREENS_LOCATION = "GREENS Location"
    HOSPITAL_VENTS_ITEM = "HOSPITAL VENTS Item"
    HOSPITAL_VENTS_LOCATION = "HOSPITAL VENTS Location"
    IMPACT_ITEM = "IMPACT Item"
    IMPACT_LOCATION = "IMPACT Location"
    INTELLIGENCE_ITEM = "INTELLIGENCE Item"
    INTELLIGENCE_LOCATION = "INTELLIGENCE Location"
    INVINCIBILITY_ITEM = "Invincibility Item"
    KILL_10_LOCATION = "Kill 10 Enemies Location"
    KILL_7_HEADSHOTS_LOCATION = "Kill 7 Enemies with Headshots Location"
    KILL_ALL_LOCATION = "Kill All Enemies Location"
    KILL_LOCATION = "Kill Location"
    LEVEL_UNLOCK_ITEM = "Level Unlock Item"
    LOWER_ADMIN_ITEM = "LOWER ADMIN Item"
    LOWER_ADMIN_LOCATION = "LOWER ADMIN Location"
    MIDDLE_ADMIN_ITEM = "MIDDLE ADMIN Item"
    MIDDLE_ADMIN_LOCATION = "MIDDLE ADMIN Location"
    MIRAGE_ITEM = "MIRAGE Item"
    MIRAGE_LOCATION = "MIRAGE Location"
    MUSEUM_ITEM = "MUSEUM Item"
    MUSEUM_LOCATION = "MUSEUM Location"
    NEBULA_ITEM = "NEBULA Item"
    NEBULA_LOCATION = "NEBULA Location"
    PARTY_MANSION_ITEM = "PARTY MANSION Item"
    PARTY_MANSION_LOCATION = "PARTY MANSION Location"
    PENTHOUSE_ITEM = "PENTHOUSE Item"
    PENTHOUSE_LOCATION = "PENTHOUSE Location"
    PORTAL_LAB_ITEM = "PORTAL LAB Item"
    PORTAL_LAB_LOCATION = "PORTAL LAB Location"
    PRISON_ITEM = "PRISON Item"
    PRISON_LOCATION = "PRISON Location"
    PRODUCTION_LAB_ITEM = "PRODUCTION LAB Item"
    PRODUCTION_LAB_LOCATION = "PRODUCTION LAB Location"
    RANK_A_LOCATION = "Obtain an A Rank Location"
    RANK_BOOSTING_ITEM = "Rank-Boosting Item"
    RANK_B_LOCATION = "Obtain a B Rank Location"
    RANK_LOCATION = "Rank Location"
    RANK_S_LOCATION = "Obtain an S Rank Location"
    RANK_S_PLUS_LOCATION = "Obtain an S+ Rank Location"
    RANK_S_PLUS_PLUS_LOCATION = "Obtain an S++ Rank Location"
    RECEPTION_ITEM = "RECEPTION Item"
    RECEPTION_LOCATION = "RECEPTION Location"
    REDHOUSE_ITEM = "REDHOUSE Item"
    REDHOUSE_LOCATION = "REDHOUSE Location"
    RED_PROCESSING_ITEM = "RED PROCESSING Item"
    RED_PROCESSING_LOCATION = "RED PROCESSING Location"
    R_D_LAB_ITEM = "R&D LAB Item"
    R_D_LAB_LOCATION = "R&D LAB Location"
    SERVER_ROOM_ITEM = "SERVER ROOM Item"
    SERVER_ROOM_LOCATION = "SERVER ROOM Location"
    STYLISH_ACTION_LICENSE_ITEM = "Stylish Action License Item"
    SUBWAY_VENTS_ITEM = "SUBWAY VENTS Item"
    SUBWAY_VENTS_LOCATION = "SUBWAY VENTS Location"
    TARGET_TIME_BEAT_LOCATION = "Beat the Target Time Location"
    TARGET_TIME_DISCOUNT_ITEM = "Target Time Discount Item"
    TARGET_TIME_LOCATION = "Target Time Location"
    THE_WALL_ITEM = "THE WALL Item"
    THE_WALL_LOCATION = "THE WALL Location"
    TOWERS_ITEM = "TOWERS Item"
    TOWERS_LOCATION = "TOWERS Location"
    TRAIN_ITEM = "TRAIN Item"
    TRAIN_LOCATION = "TRAIN Location"
    TRAIN_STATION_ITEM = "TRAIN STATION Item"
    TRAIN_STATION_LOCATION = "TRAIN STATION Location"
    TRAIN_ZERO_ITEM = "TRAIN ZERO Item"
    TRAIN_ZERO_LOCATION = "TRAIN ZERO Location"
    TRAP_ITEM = "Trap Item"
    UNLIMITED_AMMO_ITEM = "Unlimited Ammo Item"
    UNLIMITED_CANNON_AMMO_ITEM = "Unlimited Cannon Ammo Item"
    UPPER_ADMIN_ITEM = "UPPER ADMIN Item"
    UPPER_ADMIN_LOCATION = "UPPER ADMIN Location"
    VANGUARD_ITEM = "VANGUARD Item"
    VANGUARD_LOCATION = "VANGUARD Location"
    VENTS_3_ITEM = "VENTS 3 Item"
    VENTS_3_LOCATION = "VENTS 3 Location"
    WASTE_MANAGEMENT_ITEM = "WASTE MANAGEMENT Item"
    WASTE_MANAGEMENT_LOCATION = "WASTE MANAGEMENT Location"


class SeveredSteelAPTrapTypes(enum.Enum):
    BLACK_AND_WHITE = "Black and White Trap"
    BLOOM = "Bloom Trap"
    CHROMATIC = "Chromatic Trap"
    CINEMATIC = "Cinematic Trap"
    COLOR_INVERSION = "Color Inversion Trap"
    FAST_MO = "Fast-Mo Trap"
    MOBILE_GAME = "Mobile Game Trap"
    TUNNEL_VISION = "Tunnel Vision Trap"


class SeveredSteelDifficulties(enum.Enum):
    COLD_STEEL = "Cold Steel"
    TEMPERED_STEEL = "Tempered Steel"
    SEVERED_STEEL = "Severed Steel"
    SHARPENED_STEEL = "Sharpened Steel"
    MOLTEN_STEEL = "Molten Steel"


class SeveredSteelLevels(enum.Enum):
    WASTE_MANAGEMENT = "WASTE MANAGEMENT"
    EPOCH = "EPOCH"
    MIRAGE = "MIRAGE"
    VANGUARD = "VANGUARD"
    NEBULA = "NEBULA"
    CIPHER = "CIPHER"
    CROSS = "CROSS"
    IMPACT = "IMPACT"
    FLOAT = "FLOAT"
    COSMOLOGY = "COSMOLOGY"
    REDHOUSE = "REDHOUSE"
    RED_PROCESSING = "RED PROCESSING"
    CAFETERIA = "CAFETERIA"
    CYBERMEDICINE = "CYBERMEDICINE"
    CORRIDOR = "CORRIDOR"
    HOSPITAL_VENTS = "HOSPITAL VENTS"
    SUBWAY_VENTS = "SUBWAY VENTS"
    TRAIN_STATION = "TRAIN STATION"
    TRAIN = "TRAIN"
    CHECKPOINT = "CHECKPOINT"
    INTELLIGENCE = "INTELLIGENCE"
    SERVER_ROOM = "SERVER ROOM"
    ARMORY = "ARMORY"
    PRISON = "PRISON"
    VENTS_3 = "VENTS 3"
    RECEPTION = "RECEPTION"
    LOWER_ADMIN = "LOWER ADMIN"
    UPPER_ADMIN = "UPPER ADMIN"
    PORTAL_LAB = "PORTAL LAB"
    BARRACKS = "BARRACKS"
    APARTMENTS = "APARTMENTS"
    GREENS = "GREENS"
    PARTY_MANSION = "PARTY MANSION"
    CEO_OFFICE = "CEO OFFICE"
    PENTHOUSE = "PENTHOUSE"
    GARDEN = "GARDEN"
    MUSEUM = "MUSEUM"
    ESTATE = "ESTATE"
    THE_WALL = "THE WALL"
    R_D_LAB = "R&D LAB"
    PRODUCTION_LAB = "PRODUCTION LAB"
    CLEAVE = "CLEAVE"
    TRAIN_ZERO = "TRAIN ZERO"
    DATA_PRISM = "DATA PRISM"
    FOREST = "FOREST"
    MIDDLE_ADMIN = "MIDDLE ADMIN"
    TOWERS = "TOWERS"
    CITY = "CITY"
    ART_GALLERY = "ART GALLERY"
    CONSCIENCE = "CONSCIENCE"
    ESCAPISM = "ESCAPISM"


class SeveredSteelMutators(enum.Enum):
    BIG_HEADS = "Big Heads"
    TRIPLE_THREAT = "Triple Threat"
    SUPER_SLIDE = "Super Slide"
    LIMITED_SLOW_MO = "Limited Slow-Mo"
    WARRIOR_MONK = "Warrior Monk"
    PAINTBALL = "Paintball"
    SUPERKICK = "Superkick"
    MELEE_GIBS_ENEMIES = "Melee Gibs Enemies"
    ONE_IN_THE_CHAMBER = "One In The Chamber"
    SCARY_LIGHTING = "Scary Lighting"
    LOW_GRAVITY = "Low Gravity"
    FLOOR_IS_LAVA = "Floor Is Lava"
    LIKE_WATER = "Like Water"
    STEELCRAFT = "Steelcraft"
    SEE_THROUGH_WALLS = "See-Through Wall"
    THRUST_CANNON = "Thrust Cannon"
    STEELCRAWLER = "Steelcrawler"
    ENEMIES_EXPLODE_ON_DEATH = "Enemies Explode On Death"
    EXPLOSIVE_AMMO = "Explosive Ammo"
    CLOAKED = "Cloaked"
    BULLETPROOF = "Bulletproof"
    UNLIMITED_AMMO = "Unlimited Ammo"
    THROWN_WEAPONS_EXPLODE = "Thrown Weapons Explode"
    ATTACK_THE_WEAK_POINT = "Attack The Weak Point"
    TWO_X_CANNON_AMMO = "2x Cannon Ammo"
    BOOST_ROF = "Boost RoF"
    CHAIN_REACTION = "Chain Reaction"
    CRACK_TROOPS = "Crack Troops"
    DOUBLE_MAG = "Double Mag"
    EXPLODING_DOOR = "Exploding Door"
    RIP_AND_TEAR = "Rip And Tear"
    KILLS_REFILL_MAG = "Kills Refill Mag"
    FASTER_STEEL = "Faster Steel"
    EXPLOSIVE_SHIELDS = "Explosive Shields"
    FASTER_SLOMO = "Faster Slomo"
    HOLD_ON_TIGHT = "Hold On Tight"
    EXPLOSIVE_PROPS = "Explosive Props"
    EDENSYS_EXTENDED_MAGS = "EdenSys Extended Mags"
    PASSIVE_CANNON_CHARGE = "Passive Cannon Charge"
    BLOOD_FEUD = "Blood Feud"
    PERFECT_ACCURACY = "Perfect Accuracy"
    SUPER_DIVE = "Super Dive"
    SUPER_KICKSLIDE = "Super Kickslide"
    SUPER_WALL_RUN = "Super Wall Run"
    TRIPLE_JUMP = "Triple Jump"
    REBALANCED_BULLET_TIME = "Rebalanced Bullet Time"


class SeveredSteelRanks(enum.Enum):
    B = "B"
    A = "A"
    S = "S"
    S_PLUS = "S+"
    S_PLUS_PLUS = "S++"


class SeveredSteelStylishActions(enum.Enum):
    DIVE_FRAG = "Dive Frag"
    WALL_RUN_FRAG = "Wall Run Frag"
    FLIP_FRAG = "Flip Frag"
    KICKSLIDE = "Kickslide"
    SLIDE_FRAG = "Slide Frag"
    HEADSHOT = "Headshot"
    RIDING_KILL = "Riding Kill"
    SHIELD_KICKED = "Shield Kicked"
    DOOR_HIT = "Door Hit"
    EXPLOSIVE_FRAG = "Explosive Frag"
    MULTIKILL = "Multikill"
    THROW_HIT = "Throw Hit"
    CANNON_FRAG = "Cannon Frag"
    GLASS_DIVE = "Glass Dive"
    DROP_KICK = "Drop Kick"
    FALLING_FRAG = "Falling Frag"
    PROP_FRAG = "Prop Frag"
    WALL_BANG = "Wall Bang"
    STOLE_WEAPON = "Stole Weapon"
    QUICK_SHOT = "Quick Shot"
    AIR_SHOT = "Air Shot"
    KICK = "Kick"
    HEAVY_DOWN = "Heavy Down"
    JETPACK_JOYRIDE = "Jetpack Joyride"
    NICE_THROW = "Nice Throw"
    ROCKET_KICK = "Rocket Kick"
    NICE_CATCH = "Nice Catch"
    BLOW_BACK = "Blow Back"
    THREAD_THE_NEEDLE = "Thread The Needle"
    THE_TREY = "The Trey"
